// Per-session Posts state.
// Mirrors the subscribe/notify pattern used by src/library.js.
//
// Public API:
//   getPosts(sessionId)         → Post[]  (seeds from mocks on first access)
//   addPostDraft(sessionId, {network, text[], hashtags[]}) → Post
//   attachImageToDraft(sessionId, postId, imageUrl)
//   subscribe(sessionId, fn)    → unsubscribe fn

import { posts as mockPosts } from "./mocks.js?v=22";
import { isNewUser } from "./user-mode.js?v=20";

// --- Module state -------------------------------------------------------

const store = new Map(); // sessionId → Post[]
const subs = new Map(); // sessionId → Set<fn>

let idCounter = 0;
function newId() {
  idCounter += 1;
  return `draft-${Date.now().toString(36)}-${idCounter}`;
}

// --- Public API ---------------------------------------------------------

export function getPosts(sessionId) {
  if (!store.has(sessionId)) seed(sessionId);
  return store.get(sessionId);
}

// Prepend a new draft post (generated by the conversational draft flow).
// Returns the created post object so callers can reference its id.
export function addPostDraft(sessionId, { network, text, hashtags = [] }) {
  const posts = getPosts(sessionId);
  // Use the first existing post's author as a template — keeps the demo
  // looking like it belongs to the same person.
  const templateAuthor = posts[0]?.author || {
    name: "You",
    title: "",
    initials: "YO",
    connection: "1st",
    visibility: "public",
  };
  const draft = {
    id: newId(),
    author: templateAuthor,
    network: network === "x" ? "twitter" : network,
    status: "ready",
    timeLabel: "just now",
    text: Array.isArray(text) ? text : [text],
    hashtags,
    cta: "",
    hasImage: false,
    stats: { likes: 0, comments: 0, reposts: 0 },
  };
  posts.unshift(draft);
  notify(sessionId);
  return draft;
}

// Update a post's image (called from the generate-image modal callback).
export function attachImageToDraft(sessionId, postId, imageUrl) {
  const posts = getPosts(sessionId);
  const post = posts.find((p) => p.id === postId);
  if (post) {
    post.hasImage = true;
    post.imageUrl = imageUrl;
    notify(sessionId);
  }
}

export function subscribe(sessionId, fn) {
  if (!subs.has(sessionId)) subs.set(sessionId, new Set());
  subs.get(sessionId).add(fn);
  return () => {
    const set = subs.get(sessionId);
    if (set) set.delete(fn);
  };
}

// --- Internals ----------------------------------------------------------

function seed(sessionId) {
  // Mirrors library.js: new users start with an empty list so the empty-state
  // UX shows correctly. Posts are added when they draft from an idea.
  // Shallow-copy each post so edits (image attachment, etc.) don't leak
  // across sessions or mutate the shared mock array.
  store.set(sessionId, isNewUser() ? [] : mockPosts.map((p) => ({ ...p })));
}

function notify(sessionId) {
  const set = subs.get(sessionId);
  if (!set) return;
  const snapshot = store.get(sessionId).slice();
  set.forEach((fn) => fn(snapshot));
}
